expressions in "query", iterable parameters
php-etl/sql-plugin pull request #26
Opened 2023-06-19 12:35 UTC by clemzarch

![image](https://github.com/php-etl/sql-plugin/assets/28787740/cdc86d8d-b59f-4b3d-95b7-abf8ffb1eae5)

![image](https://github.com/php-etl/sql-plugin/assets/28787740/108d23ec-1f5c-401c-b824-1ec7e8c69f44)

2023-06-29 10:13 UTC, JoMessina reviewed
Je valide la structure et le paramétrage qui m'a l'air bon mais je n'ai pas tout compris à la logique dans les compile

2023-06-29 15:13 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +    public function addStringParam(int|string $key, Node\Expr $param, null|bool $iterable = false): StepBuilderInterface
```suggestion
    public function addStringParam(int|string $key, Node\Expr $param, null|bool $isIterable = false): StepBuilderInterface
```

2023-06-29 15:22 UTC, sebprt requested changes, later dismissed

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +            'iterable' => $iterable,
```suggestion
            'isIterable' => $iterable,
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +    public function addIntegerParam(int|string $key, Node\Expr $param, null|bool $iterable = false): StepBuilderInterface
```suggestion
    public function addIntegerParam(int|string $key, Node\Expr $param, bool $isIterable = false): StepBuilderInterface
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +            'iterable' => $iterable,
```suggestion
            'isIterable' => $iterable,
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +    public function addBooleanParam(int|string $key, Node\Expr $param, null|bool $iterable = false): StepBuilderInterface
```suggestion
    public function addBooleanParam(int|string $key, Node\Expr $param, bool $isIterable = false): StepBuilderInterface
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +            'iterable' => $iterable,
```suggestion
            'isIterable' => $isIterable,
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +    public function addDateParam(int|string $key, Node\Expr $param, null|bool $iterable = false): self
```suggestion
    public function addDateParam(int|string $key, Node\Expr $param, bool $isIterable = false): self
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +            'iterable' => $iterable,
```suggestion
            'isIterable' => $isIterable,
```

2023-06-29 15:22 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +            'iterable' => $iterable,
Je trouve ça un peu bizarre de devoir passer une option `isIterable` pour chaque arguments.

2023-06-29 15:22 UTC, sebprt commented on src/Factory/Loader.php
> +
C'est peut être ici où un niveau au dessus qu'il faudrait améliorer la façon de rendre un paramètre itérable

2023-07-03 08:21 UTC, JoMessina approved these changes

2023-07-05 13:32 UTC, gplanchat commented on src/Builder/AlternativeLoader.php
> +    public function getParameters(): iterable
**❔ question:** L'ancien nom de la méthode me paraissait correct, pourquoi est-ce que tu l'as modifié ?
‏

2023-07-05 13:37 UTC, clemzarch commented on src/Builder/AlternativeLoader.php
> +    public function getParameters(): iterable
c'est juste une nouvelle fonction.
Avant `getNode` appelait directement `compileParameters`. Maintenant `getNode` apelle `getParameters` qui fait plusieurs `compileParameters`

2023-07-10 07:44 UTC, merged