Fixed the connection options config + updated tests + updated depende…
php-etl/sql-plugin pull request #5
Opened 2022-04-15 15:01 UTC by sebprt

Correction de la configuration sur les options de connection (`persistent`)
Modification de la configuration de `parameters` pour ajouter une nouvelle option `type` (bool, int) pour qu'il y est un paramètre `\PDO::PARAM_BOOL` lors de la compilation

![Capture d’écran 2022-04-15 à 17 01 01](https://user-images.githubusercontent.com/47692802/163586684-3cc28ccf-beea-4cdf-8a7c-13ea20e84614.png)

2022-04-20 08:27 UTC, gplanchat requested changes

2022-04-20 08:27 UTC, gplanchat commented on composer.json
> +        "php-etl/configurator-contracts": "0.4.x-dev",
non, on ne fait jamais un require sur une branche dev

2022-04-20 08:47 UTC, gplanchat requested changes

2022-04-20 08:47 UTC, gplanchat commented on src/Builder/DTO/Parameter.php
> +        public ?string $type = null,
Je ne suis pas fan de cette implémentation. Pourquoi est-ce que'ici tu n'utilises pas un enum ou des classes spécialisées pour chacun de tes 2 cas ?

Utiliser une chaîne de caractères partout dans ton code par convention et sans avoir écrit de tests, ça ne va pas t'alerter sur des fautes de frappe, tu vas rechercher le problème pendant des heures. Et le jour où tu refacotrises rien ne sera automatisable.

Tout repose sur le bon fonctionnement sur ton correcteur orthographique dans PHPStorm.

2022-04-20 08:47 UTC, gplanchat commented on src/Builder/AlternativeLoader.php
> +    public function addParam(Parameter $parameter): StepBuilderInterface
Pourquoi est-ce que tu obliges le développeur à créer ces objets `Parameter`, qui n'est que la somme des 2 précédents arguments de la méthode ?

Cet objet `Parameter` est un détail d'implémentation. il pourrait être géré par tes classes `StepBuilderInterface` pour faire leur sauce mais n'apporte rien d'autre à ton utilisateur qu'un peu plus de complexité.

Cet objet n'est utilisé que par ces classes `StepBuilderInterface`, il n'en sort jamais et n'est jamais partagé.

2022-04-20 08:47 UTC, gplanchat commented on tests/functional/Builder/ExtractorTest.php
> +                        ]
On a non seulement un changement du format, mais une DX qui est moins bonne : la config à écrire est moins pratique. Je préférais l'ancienne syntaxe.

2022-04-20 08:47 UTC, gplanchat commented on tests/functional/PipelineRunner.php
> +}
Cette classe n'existe pas dans le paquet `php-etl/phpunit-extension` ?

2022-04-21 07:00 UTC, sebprt commented on tests/functional/PipelineRunner.php
> +}
Non elle n'existe pas, est ce qu'il faut la rajouter ?

2022-04-21 15:28 UTC, sebprt commented on src/Builder/AlternativeLoader.php
> +    public function addParam(Parameter $parameter): StepBuilderInterface
J'ai supprimé cet object et retravaillé la façon dont est géré le type d'un argument.

2022-04-21 15:28 UTC, sebprt commented on tests/functional/Builder/ExtractorTest.php
> +                        ]
J'ai remis l'ancien format

2022-04-21 15:29 UTC, sebprt commented on src/Builder/DTO/Parameter.php
> +        public ?string $type = null,
J'ai retravaillé la façon dont est géré le type d'un argument

2022-05-03 07:45 UTC, gplanchat requested changes

2022-05-03 07:45 UTC, gplanchat commented on src/Configuration/Parameters.php
> +                        ->values(['boolean', 'integer', 'string'])
il faudrait que l'on prévoit les cas de `date`, `datetime`, `json` et `binary`

2022-05-03 07:45 UTC, gplanchat commented on tests/functional/Builder/ExtractorTest.php
> +                        ]
J'ai pas l'impression qu'on soit revenu à l'ancienne syntaxe `['identifier' => '@=3']`

2022-05-03 14:26 UTC, sebprt commented on tests/functional/Builder/ExtractorTest.php
> +                        ]
Je suis revenu à l'ancienne syntaxe

2022-05-16 09:23 UTC, gplanchat approved these changes

2022-05-16 09:23 UTC, merged